### PR TITLE
Choose poke ball based on CP encounter.

### PR DESCRIPTION
**Pull request by pkiers**
Choosing a ball based on the CP of the encounter
0-100 ITEM_POKE_BALL
100-400 ITEM_GREAT_BALL
400-?? ITEM_ULTRA_BALL

### CODE REVIEW

**Comment by mich3lam** [comment]
https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/111

**Comment by beminee** [comment]
#111 has better logic

**Comment by Spegeli** [comment]
There is already a better Solution:
https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/111

**Comment by pkiers** [comment]
Closing this :)

**Pull request closed without merging**
