### PR TITLE
New Devs' Helper & Tweaks

### PR DESCRIPTION
**Pull request by RoachxD**
- Removed unused directives (e.g "using System;"), add them when/if needed, the code looks cleaner.
 - Using specified type instead of vars (So new devs can quickly understand the code).
 - Converted recursion to iteration when/where possible.
 - Converted to static when/where possible (Performance++).
 - Simplified and re-indented some code to be more readable.
 - Fixed all code-based warnings.

PS1: This PR was made to help New Devs understand faster the project.
PS2: I will PR another commit with some performance tweaks later (I'm a bit tired).
PS3: Sorry for the "Revert Revert" but as I said, I'm a little tired.

### CODE REVIEW

**Comment by RoachxD** [comment]
Also, shouldn't "MiscEnums" be part of "PokemonGo.RocketAPI.Enums" namespace?

**Comment by jshield** [comment]
We may want to implement some code quality metrics (sonarlint?) and a set out a basic coding style guideline. Not sure how to integrate into GitHub though.

**Comment by RoachxD** [comment]
I don't think it is possible to integrate something like this into GitHub, or I just lived in a cave by now and there is a way.

**Comment by OranShuster** [comment]
you can't use any lint/coding styles algorithms on github afaik. you can only monitor the PR

**Comment by RoachxD** [comment]
As I've known then :)

**Comment by FeroxRev** [comment]
Thanks for the effort.

However:
*I'm a strong fan of var which allows me to develop faster and in my opinion looks cleaner, so i'm going to adhere to this.
*This code is not really meant for noobs, but should still be understandable (even with var)
*Don't agree on removing System namespace
*What's wrong with a recursive loop? We don't need the performance win. No use in refactoring unneeded stuff.
*We are not really in need of performance at all as current implementation uses no resources at all

Sorry if I sound a bit harsh, but I'd like to keep the current style. Next time perhaps ask me when you want to do a full code base refactor before spending the time. Sorry again for the time spent.

**Comment by RoachxD** [comment]
Well, I tried, there's no problem, I will try to help you in some other way tomorrow.

**Pull request closed without merging**
