### PR TITLE
Small typo

### PR DESCRIPTION
**Pull request by Bitsnoxx**

### CODE REVIEW

**Comment by Advancensar** [comment]
While you are at it change this one too
    [pbr::OriginalName("GEODUGE")] Geoduge = 74,
to
    [pbr::OriginalName("GEODUDE")] Geodude = 74,

**Comment by Bitsnoxx** [comment]
There!

**Comment by Bitsnoxx** [comment]
There seem to be a issue with Nidoran, Im not sure why - Im a bit tired atm, can look at more tomorrow!

**Comment by FeroxRev** [comment]
Rejecting because the classes are auto-generated and your changes will just be overridden in the future.

**Pull request closed without merging**
