### PR TITLE
Added old google authentication with a new AuthType 

### PR DESCRIPTION
**Pull request by Da-Teach**
Needed because the new authentication method doesn't work with two factor authentication.

### CODE REVIEW

**Comment by Da-Teach** [comment]
Whoops, should have tested, doesn't work yet (throws an 401-unauthorized error)

**Comment by Da-Teach** [comment]
I'm stupid :)

**Comment by FeroxRev** [comment]
You can use an application pw and still use 2fa

**Comment by Da-Teach** [comment]
Yes, I was being stupid :)

2016-08-02 17:26 GMT+02:00 Ferox notifications@github.com:

**Pull request closed without merging**
