### PR TITLE
Human like walking rev2

### PR DESCRIPTION
**Pull request by UntilSunrise**
We can walk a direct line towards our destination an we can set a walking speed in km/h.

### CODE REVIEW

**Comment by UntilSunrise** [comment]
Also sorting pokestop by distance

**Comment by Mavmins** [comment]
Is this implemented in your version ? This is fantastic

**Comment by MonsterMMORPG** [comment]
ye please merge this one

this walking is awesome and mandatory

@FeroxRev

**Comment by DaniilSokolyuk** [comment]
Nice work

**Comment by FeroxRev** [comment]
Awesome, thanks

**Comment by DaniilSokolyuk** [comment]
Why reverted?
@FeroxRev

**Comment by FeroxRev** [comment]
Unfortunately there's a bug in it, didn't have time to figure it out, so reverted for now!

**Pull request merged**
