### PR TITLE
Update Check / Notifies you if no pokeballs are left

### PR DESCRIPTION
**Pull request by NecronomiconCoding**

### CODE REVIEW

**Comment by Spegeli** [comment]
Maybe you can change the No Pokeball output to something like:

````
Logger.Write($"No pokeball available :( - We missed a {pokemon.PokemonId} with CP {encounterPokemonResponse?.WildPokemon?.PokemonData?.Cp}", LogLevel.Info);
````

**Comment by FeroxRev** [comment]
I really like to keep focusing on features and not in logging as much to the user or keeping them updated  that there is a new version. Shouldn't be in this repo. This repo would otherwise explode and decrease maintainability

**Comment by Spegeli** [comment]
Most of the people love logging because they want to see what is happen.

**Comment by navidemad** [comment]
👍

**Pull request closed without merging**
