### PR TITLE
Added multi-message decoding

### PR DESCRIPTION
**Pull request by Da-Teach**
This works, maybe not the most elegant solution but seeing as (I think) nothing uses more than 5 request messages, this works.

### CODE REVIEW

**Comment by FeroxRev** [comment]
Hi Da-Teach! Nice to see you here! 

Merging this in, cool!

**Comment by Da-Teach** [comment]
Just playing around :)

Bit boring at work at the moment, so spending some work-hours on a bot
(based on your first version).

2016-08-02 11:24 GMT+02:00 Ferox notifications@github.com:

**Comment by StEaLtHmAn** [comment]
Hi Da-Teach,

I don't understand why you would make the "GetMapObjects()" method request so much.

when calling a method named "GetMapObjects()" i dont expect to receive GetHatchedEggsResponse, GetInventoryResponse, CheckAwardedBadgesResponse, DownloadSettingsResponse

Why not just make another method to return these things?

**Comment by Da-Teach** [comment]
GetMapObjects always requested these messages, this change just makes the responses available.

As far was as "why", I'm guessing they need to be done in that order (in the same message to the server) because the game does this too.

**Pull request merged**
