### PR TITLE
add Program.TransferAllGivenPokemons(...) and Program.EvolveAllGivenPokemons(...)

### PR DESCRIPTION
**Pull request by martin-podlubny**
Building on top of https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/50 which introduced the `Client.TransferPokemon(...)` and `Client.EvolvePokemon(...)`

### CODE REVIEW

**Comment by martin-podlubny** [comment]
Should review/merge the first PR I think :)

**Comment by Maufeat** [comment]
Executed that EvolveAllGivenPokemons, put all my pokemons in, and it tried to evlove my Voltorb the whole time but it can't (not enough candys) but it says it is successfully evolved in a loop. 

Like this:

> Evolved V0100PokemonVoltorb successfully for 0xp
Evolved V0100PokemonVoltorb successfully for 0xp
Evolved V0100PokemonVoltorb successfully for 0xp
Evolved V0100PokemonVoltorb successfully for 0xp
Evolved V0100PokemonVoltorb successfully for 0xp

**Comment by martin-podlubny** [comment]
@Maufeat Don't know, haven't really try evolving yet :D Fix it, I don't have time ATM :)

**Comment by Maufeat** [comment]
Oki

**Comment by martin-podlubny** [comment]
Using this in https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/53

**Pull request merged**
