### PR TITLE
add Program.TransferAllButStrongestUnwantedPokemon(...)

### PR DESCRIPTION
**Pull request by martin-podlubny**
Building on top of https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/51 which introduced the `Program.TransferAllGivenPokemons(...) and Program.EvolveAllGivenPokemons(...)`

### CODE REVIEW

**Comment by FeroxRev** [comment]
Cool stuff, all these logic related ones will be looked at later!

**Comment by MonsterMMORPG** [comment]
awesome i can implement this and modify it to release only non perfect catches :D

**Comment by Trical** [comment]
@MonsterMMORPG what do you mean with a non perfect catch?

**Comment by MonsterMMORPG** [comment]
@Trical  if all iv values are 15 that means it is a perfect catch. all other pokemon should be released

**Comment by MonsterMMORPG** [comment]
@martin-podlubny  how can i locally merge your pull?

here question http://stackoverflow.com/questions/38483302/how-can-i-fetch-unmerged-pull-requests-that-i-do-not-own

**Comment by martin-podlubny** [comment]
@MonsterMMORPG you could add my fork as a second remote to your local repo, checkout the branch that the PR is for, and merge it into whatever branch you have going on (probably your local master)

**Comment by MonsterMMORPG** [comment]
@martin-podlubny  so this is your branch right?

https://github.com/martin-podlubny/Pokemon-Go-Rocket-API/tree/transfer-all-but-strongest-unwanted-pokemon

now what command do i need to merge it?

**Comment by martin-podlubny** [comment]
@MonsterMMORPG At the risk of sounding a bit rude: you want to google around a few git tutorials to get more comfortable with git :) Then you can google about on how to do specific things as a memory refresher... 

But to answer your question: you use `git merge` to merge one git branch into another :laughing:

**Comment by michaelowens** [comment]
Had to do some changes, but I managed to get this work in my local project. Awesome addition!

Transfering

**Comment by MonsterMMORPG** [comment]
i still can not figure out how to merge your branch with the original master branch on my repository :(

**Comment by martin-podlubny** [comment]
@michaelowens that UI wrapper is pretty neat! Cuz it's one thing to just run the farming bot.. But it's another to have a pogo toolkit app where you can choose from actions to do nicely. Like listing your pokemon, your inventory, your eggs, using items, batch transferring pokemon (maybe even by hitting checkboxes next to them), batch evolving pokemon etc :) 

That on public repo anywhere?

**Comment by michaelowens** [comment]
@martin-podlubny That's pretty much what I was thinking of working on. Would love to see more info in the UI and eventually even be able to use it as a bot or as a tool to play the game. I want all those features you just mentioned and add features like clicking on map would walk to that position, show all pokestops/gyms nearby and when you click on them you can actually make it attack them. Maybe eventually even have it so it can run multiple bots and you could just use it to farm gyms.

Right now it's just locally on my machine, I simple added a project to the solution after cloning it. I'll have to fork it and maybe move it to another branch. This also is really bad code most likely, as I'm not much of a C# developer.

**Comment by blackms** [comment]
@michaelowens would you mind share it?

**Comment by jshield** [comment]
@michaelowens what control are you using for the gmap?

**Comment by martin-podlubny** [comment]
@michaelowens have a look at feature request [WPF app to use the library #69](https://github.com/FeroxRev/Pokemon-Go-Rocket-API/issues/69) ... Maybe if you discuss with @FeroxRev this WPF client should live alongside the CLI client and the core libraries for API access and logic :)

**Comment by michaelowens** [comment]
@martin-podlubny @blackms I'll see if I can fork it now and push it.

@jshield [GMap.NET](https://greatmaps.codeplex.com) (I got it of NuGet)

**Comment by mich3lam** [comment]
@michaelowens Oh wow! that looks awesome, please do share with us that love!

**Comment by michaelowens** [comment]
Alright, like I mentioned before: The code is messy and more like a prototype. I'm not much of a C# developer, so I did what I could find to get it to work, that's about it.

https://github.com/michaelowens/Pokemon-Go-Rocket-API/tree/desktop-ui

**Comment by chancity** [comment]
@michaelowens Thanks, looks good.

**Comment by mich3lam** [comment]
@michaelowens can't seem to find the file I tell it to trasnfer it or no

**Comment by FeroxRev** [comment]
@martin-podlubny  Yes I'd like to see the WPF as a separate project in this repo :+1:

**Comment by michaelowens** [comment]
@mich3lam Which file? It was giving me an error after I changed it to the fork, but closing and re-opening Form1.cs fixed it for me.

**Comment by mich3lam** [comment]
@michaelowens i mean, at what file in the project does the auto-trasnfer thing know what to trasnfer and what not

**Comment by michaelowens** [comment]
@mich3lam I right, my bad, I misunderstood your question. It's basically a copy from this pull request, so near the bottom in `Form1.cs` you'll find the method `TransferUnwantedPokemon` which holds an array of "unwanted" types.

**Comment by mich3lam** [comment]
@michaelowens thank you!

**Comment by mich3lam** [comment]
@michaelowens 1 more quick question. how do i configure it to login with google instead of the login with ptc thing inside gui?

**Comment by michaelowens** [comment]
@mich3lam Right now it just uses the setting in `Settings.cs` file in the RocketAPI project.

**Comment by mich3lam** [comment]
so i should changhe it to:
        public const AuthType AuthType = Enums.AuthType.Google;
or what? I am sorry, i just cant figure it out.. how do i login after that .. im trying everything here haha

**Comment by mich3lam** [comment]
nvm, managed to do it! had to open it first on console, get the code, put it in setting to autologin then use ui

**Comment by michaelowens** [comment]
Ah, good you got it working. I haven't used Google Login yet, so I don't know how it works in this project, but I guess there would have to be some changes then for it.

**Comment by blackms** [comment]
@michaelowens it perfectly works, I just changed to Console Application inside Properties in order to spwawn the console which show the code to put inside google.com/device that's all...

**Pull request merged**
