### PR TITLE
Added Max CP percentage calculation based on Individual Values

### PR DESCRIPTION
**Pull request by 5andr0**
Added IV perfect percentage calculation and a transfer block if the pokemon is >85% perfect. Also displays the percentage when a pokemon is caught. This is good to know because you can always level up a 100% perfect Pokemon to max CP. IV's also stay the same after evolution. So it's worth it to keep a lowlvl perfect Dratini for example.

### CODE REVIEW

**Comment by Zeromark30** [comment]
that was quick. https://github.com/FeroxRev/Pokemon-Go-Rocket-API/issues/257

**Comment by navidemad** [comment]
I saw on reddit some more complex formula but your formula seems to be better than nothing.

**Comment by 5andr0** [comment]
@navidemad can you try to find it again and link it please?

**Comment by Zeromark30** [comment]
https://www.reddit.com/r/TheSilphRoad/comments/4tqddw/guide_to_determine_exact_ivs_using_mitm_proxy/
we dont need that because the game tells us the IVs directly.

**Comment by Intrusion** [comment]
https://pokeassistant.com/main/ivcalculator

not sure if this helps. it has an explanation of the calculations it uses down below.

**Comment by Merudo** [comment]
Also the pokemon go optimizer: https://github.com/justinleewells/pogo-optimizer

**Comment by Zeromark30** [comment]
the relavent code from pokemon go optimizer
`    formatted = _.map(formatted, function (entry) {
      if (entry.individual_stamina === undefined) entry.individual_stamina = 0;
      if (entry.individual_attack === undefined)  entry.individual_attack  = 0;
      if (entry.individual_defense === undefined) entry.individual_defense = 0;
      entry.power_quotient = (entry.individual_stamina + entry.individual_attack + entry.individual_defense) / 45;
      var data = _.find(PokemonData, function (pokemon) {
        return (pokemon.Name.toUpperCase() == entry.pokemon_id || pokemon.AltName == entry.pokemon_id);
      });`

**Comment by 5andr0** [comment]
Thanks @Intrusion to point out that Attack IV is more valuable than the others. I'll make a new formula. So pokemon go optimizer is also wrong (or too simplified)

**Comment by Jashooa** [comment]
@5andr0 I'm pretty sure your original calculation was right, it looks like the new calculation is partly how the CP is determined by weighing ATK more.

We don't need to know the base stats as we have direct access to the IVs, so just returning a % of how close they are to perfect 15/15/15 like you originally had would be best.

**Comment by Merudo** [comment]
I thought the base stats were known? https://gist.github.com/anonymous/540700108cf0f051e11f70273e9e2590

In any case, do we know for sure that the effect of ATK & DEF is through CP, or is CP just some arbitrary number roughly indicating strength? As Jashooa points out, weighting ATK more only makes sense if it indeed do more.

**Comment by Jashooa** [comment]
CP is just a rough estimate to display the strength of the pokemon.

We mostly care about the IVs as they are the values that determine what potential strength the pokemon will have when powered up.

**Comment by 5andr0** [comment]
@Jashooa we are calculating the percentage of the difference between the CP of a pokemon with 0,0,0 ivs -> 0% and 15,15,15 -> 100%. IV_attack gives more CP points than the other ivs, thus it has to be weighted more.
@Merudo yes we know the base stats, but i'm talking about the code. The api doesn't have these values, so the current calculation is based on a pokemon which would have equal base stats. The calculation will be slightly off when a pokemon has way more stamina than attack or vice versa.

**Comment by Jashooa** [comment]
@5andr0 but it's the Atk IV that's weighted more in the calculation of the CP, weighting it more in calculation of perfect IV is like calculating between 0/0/0 IVs and 30/15/15 IVs which is wrong.

**Comment by 5andr0** [comment]
@Jashooa We are not calculating perfect IV stats. We want to know how perfectly close to max CP it is. And 15 atk/0 def/0 sta is much closer to max CP than 0/15 def /0.

I just found the StatsAttributes proto template in the code. But i have no idea how to access it based on the PokemonType. Could anybody help me with that?

**Comment by Jashooa** [comment]
@5andr0 I see, I was just confused as it was titled "perfect Poke Individual Values percentage calculation".

**Comment by Merudo** [comment]
@5andr0 the game knows the name of the Pokemon, why can't we just add the base stats info ourselves? Let just store a matrix of base stats number corresponding to all the pokemon, & pick a row depending on the pokemon we catch. Easy no?

**Pull request merged**
