### PR TITLE
Time shown on messages

### PR DESCRIPTION
**Pull request by DidUknowiPwn**
Replaced System.Console.WriteLine to Utils.PrintConsole simpler in a sense.

Mainly for giving appropriate time in each message to know what's going on. 
http://i.imgur.com/dv57HtV.png

### CODE REVIEW

**Comment by DaniilSokolyuk** [comment]
I think need IConsole or ILogger interface for implementing in logic part.

**Comment by jshield** [comment]
I agree log4net is in the backlog of features to implement.

**Comment by DidUknowiPwn** [comment]
Whatever seems better I only know of this method to only display on console window rather than logging each thing, as I haven't used C# a lot.

**Comment by Spegeli** [comment]
Does Utils.PrintConsole supports different colors?
otherwise i would use:

````
        public static void Normal(ConsoleColor color, string text)
        {
            ConsoleColor originalColor = System.Console.ForegroundColor;
            System.Console.ForegroundColor = color;
            System.Console.WriteLine($"[{DateTime.Now.ToString("HH:mm:ss")}] " + text);
            System.Console.ForegroundColor = originalColor;
        }
````
then we can use
````
Logging.Normal(ConsoleColor.DarkYellow, $"Transfer {duplicatePokemon.PokemonId} with CP {duplicatePokemon.Cp}");
````
to get a nice DarkYellow Output with Time ;-)

**Comment by MonsterMMORPG** [comment]
i have tried this and it gave me max memory error lol :D

**Comment by FeroxRev** [comment]
This PR contains too much random stuff not related to time logging. Have to reject it.

**Pull request closed without merging**
