### PR TITLE
Possibility to filter pokemon catching.

### PR DESCRIPTION
**Pull request by pkiers**
Possibility to only catch or exclude certain types of pokemon catching.

### CODE REVIEW

**Comment by tw88** [comment]
Isnt it just better (xp wise) to catch everything and send "trash" away afterwards?

**Comment by blackms** [comment]
Yes, in order also to have more candies for evolutions and power ups.

**Comment by FeroxRev** [comment]
Agree, could you elaborate on the purpose?

**Comment by pkiers** [comment]
Had just made this because the option of transfer wasn't there yet. Wanted only pigeons for evolution. But can close this one :)

**Pull request closed without merging**
