### PR TITLE
Attempt to fix Google Auth Expiration Token

### PR DESCRIPTION
**Pull request by nowayrlz**
It solved for me, anything let me know ;)

### CODE REVIEW

**Comment by AssHole12** [comment]
Where do I put in this code? 
Sorry im not that well known in C#

**Comment by nowayrlz** [comment]
Just copy the hole file and replace GoogleLogin.cs

**Comment by AssHole12** [comment]
cant find that file, where is it?

**Comment by AssHole12** [comment]
there is just a logingoogle function, no cs

**Comment by jshield** [comment]
do you know how to merge a branch in git?

**Comment by AssHole12** [comment]
No not really

**Comment by Spegeli** [comment]
This solution seems working. 
My Google Acc is running since ~60 Minutes without any issues ^^

**Comment by Spegeli** [comment]
Seems not working.
Was running fine for ~60 Minutes, then i get Errors and after a restart i get now:

````
[11:45:32] Exception: System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: value
   bei Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   bei PokemonGo.RocketAPI.GeneratedCode.Request.Types.AuthInfo.Types.JWT.set_Contents(String value) in E:\Pokemon GO\Pokemon-Go-Rocket-API\FeroxRev\PokemonGo.RocketAPI\GeneratedCode\Request.cs:Zeile 1250.
   bei PokemonGo.RocketAPI.Helpers.RequestBuilder.GetInitialRequest(String authToken, AuthType authType, Double lat, Double lng, Double altitude, Requests[] customRequests) in E:\Pokemon GO\Pokemon-Go-Rocket-API\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:Zeile 19.
   bei PokemonGo.RocketAPI.Helpers.RequestBuilder.GetInitialRequest(String authToken, AuthType authType, Double lat, Double lng, Double altitude, RequestType[] customRequestTypes) in E:\Pokemon GO\Pokemon-Go-Rocket-API\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:Zeile 47.
   bei PokemonGo.RocketAPI.Client.<SetServer>d__13.MoveNext() in E:\Pokemon GO\Pokemon-Go-Rocket-API\FeroxRev\PokemonGo.RocketAPI\Client.cs:Zeile 97.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<Execute>d__5.MoveNext() in E:\Pokemon GO\Pokemon-Go-Rocket-API\FeroxRev\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 48.
````

**Comment by FeroxRev** [comment]
Cool stuff!

**Pull request merged**
