### PR TITLE
Disable magikarp evolving if cp < 120

### PR DESCRIPTION
**Pull request by Snufkins**
Checks if the pokemon is Magikarp and cp is less than 120.

### CODE REVIEW

**Comment by Lennix** [comment]
I'm still puzzled why that's relevant. What's up with magikarp and the magical 120 cp mark?

**Comment by Snufkins** [comment]
Nothing magical about 120 CP - It was just a base point for me, you can change it to larger / smaller. Mainly this is to avoid low carps getting evolved (I got a 111 CP Gyardos, not exactly worth 400 candy).

**Comment by jshield** [comment]
This should be generalised to be configurable in settings for all Pokemon IMHO, if it is to be accepted at all.

**Comment by Snufkins** [comment]
The easier the better - Just imagined this as a fix before someone else wastes 400 candy.

**Comment by v4sp1** [comment]
@Lennix because this pkmon got the best multiplicator coeficient when it's time to evolve, and time a lots and a lots of time to evolve. and so, let the bot handling evo is terrible, cause you'll lost everything for the "wrong" one.
But i agree with @jshield when stating it should be configurable for all pokemon

**Comment by michaelowens** [comment]
I don't think this is the job of the API. The API gives you the option to evolve, it's up to the implementation on *what* you want to evolve.

**Pull request closed without merging**
