### PR TITLE
PTC Length max change

### PR DESCRIPTION
**Pull request by Iterer**
https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/279 with a more clean code.

### CODE REVIEW

**Comment by problemz** [comment]
Maybe don´t tell everybody your login details ...

**Comment by jshield** [comment]
@problemz no matter how hard we try, people still find a way to do it.

**Comment by AlginMaduro** [comment]
i would indeed change ur password now :P

**Comment by jshield** [comment]
@Iterer a file that is committed to git cannot be subsequently ignored without deleting it from the repo.

Also this PR is now well and truly out side of original scope.

**Comment by Iterer** [comment]
Yeah I saw it afterward don't worry I changed my password.

**Comment by FeroxRev** [comment]
Remove your password :D 

Anyway closing because this might change later as @jshield mentioned

**Pull request closed without merging**
