### PR TITLE
Greatly reduced complexity of GetBestBall logic

### PR DESCRIPTION
**Pull request by danielekeroth**

### CODE REVIEW

**Comment by Spegeli** [comment]
Question for my own Fork:

How i let them "return MiscEnums.Item.ITEM_UNKNOWN" when we dont have any pokeball?

**Comment by danielekeroth** [comment]
@Spegeli I would just add a check if the grouped query contains zero groups, then return MiscEnums.Item.ITEM_UNKNOWN before checking any of the other conditions.

Like:

            if (balls.Count == 0) return MiscEnums.Item.ITEM_UNKNOWN;

**Comment by navidemad** [comment]
Using a masterball when the pokemon has 1000 cp is useless, how could we select it only when its a legendary pokemon like mewtwo or something similar?

**Comment by Spegeli** [comment]
yeah i would increase the masterball to >= 1500

**Comment by Bitsnoxx** [comment]
I personally mean that this is best:
600   > Great ball
1500 > Ultra Ball

AND
If CP > 700, use berry

**Comment by FeroxRev** [comment]
Are you sure this code works?
var berries = inventoryBalls.Count(p => (ItemId) p.Item_ == ItemId.ItemRazzBerry);

the berry count resides in a single inventoryItem and has a count attribute

**Comment by danielekeroth** [comment]
@FeroxRev I've been running that code myself. However, I've never run out of berries so can't verify if that scenario works or not when you have no berries.

**Pull request closed without merging**
