### PR TITLE
Efficient path generation to prevent large jumps.

### PR DESCRIPTION
**Pull request by Hardell**
This generates an efficient circular path to prevent large jumps. Takes roughly 3 seconds for Central Park in NY and makes the stops to be 100m from each other on average.

Example: http://i.imgur.com/kUua3SP.png

### CODE REVIEW

**Comment by whalleyboi** [comment]
Seems to work great! good job

**Comment by DaniilSokolyuk** [comment]
very great with #235 and #191

**Comment by AdnanCukur** [comment]
This works great after the first jump, the first jump always seems to be 500m + .

**Comment by Hardell** [comment]
True, I forgot to shift the final path so that it starts with the closest pokestop. I'm leaving home right now and I won't be able to do that over the weekend so if someone else could do it that'd be great. It shouldn't take more than 5 minutes. If not, I'll do it when I get back.

**Comment by DaniilSokolyuk** [comment]
This is Dijkstra's algorithm right? Correct me if I'm wrong.
Really ignore nearly 4 poketstops, need calclulate path from start coordinates

**Comment by FeroxRev** [comment]
Ahh i justed merged the other one in =/

**Comment by TFMvdBroek** [comment]
Does this work more efficient/faster than UntilSunrise's Human walking?

**Comment by AdnanCukur** [comment]
This isnt a walking simulator, its just a pokestop sorter. It sorts the pokestop list so the bot travels the shortest amount of distance to get all pokestops.

**Comment by TFMvdBroek** [comment]
Ah ok, now i understand why it uses a circular path, clever!
What "other one" did Ferox refer to then, #270?

**Pull request closed without merging**
