### PR TITLE
Display Experience per Hour in the Console Title

### PR DESCRIPTION
**Pull request by Novalys**
I saw a request to display the experience per hour rate that could be useful. Currently it's set to be displayed on the title of the console (as nothing was there, could be changed if needed).

exp_per_hour

### CODE REVIEW

**Comment by Spegeli** [comment]
Was me with the request ;-)
thx for your solution.

**Comment by jshield** [comment]
Can you expose those statistics from the Logic class and in the Console project implement the update title functionality?

**Comment by jshield** [comment]
you'll need to split out your original PR into a separate branch and resubmit this.

**Comment by FeroxRev** [comment]
Sorry again, but too much unrelated stuff in your PR. Can you remerge the current master branch into yours and remove changes to app.config etc?

**Pull request closed without merging**
