### PR TITLE
add Program.GetCandyAmountForPokemon(...)

### PR DESCRIPTION
**Pull request by martin-podlubny**

### CODE REVIEW

**Comment by ArcticXWolf** [comment]
Ah, are you aware of the fact, that pokemonId got renamed to pokemonType in #38?

**Comment by martin-podlubny** [comment]
I think so, I mean this PR uses `PokemonType` at 
```C#
var pokemons = inventory.Payload[0].Bag.Items.Select(i => i.Item?.Pokemon).Where(p => p != null && p?.PokemonType != PokemonIds.PokemonUnset);
```

**Comment by ArcticXWolf** [comment]
Yeah, like I said, I changed the Property name, but not the enum name. As soon as your PR is merged, I will correct it.

**Comment by FeroxRev** [comment]
We have this in current version :D

**Pull request closed without merging**
