### PR TITLE
Skip expired pokestops.

### PR DESCRIPTION
**Pull request by pkiers**
Skip pokestops that have been expired since last fetch.

### CODE REVIEW

**Comment by navidemad** [comment]
👍

**Comment by FeroxRev** [comment]
Look closely. We already have this

**Comment by pkiers** [comment]
@FeroxRev Or I am overlooking something fully but I can't find that. I fetched all the pokestops and then itterates throught them with 15 sec delay in between right? It doesn't update the collection right?

**Comment by UntilSunrise** [comment]
var pokeStops = mapObjects.MapCells.SelectMany(i => i.Forts).Where(i => i.Type == FortType.Checkpoint && **i.CooldownCompleteTimestampMs < DateTime.UtcNow.ToUnixTime()**)

**Comment by pkiers** [comment]
Yes on that moment, but it takes 15 seconds per pokestop to itterate throught them. So they can expire in the meanwhile

**Pull request closed without merging**
