### PR TITLE
Updated logic to keep IV >80%

### PR DESCRIPTION
**Pull request by Unentertained**
Prevents transferring high IV pokemon.
[https://www.reddit.com/r/pokemongodev/comments/4txy32/pokemon_go_bot_user_friendly_open_source/d5lnb9y](url)

### CODE REVIEW

**Comment by VanStorm** [comment]
I like this idea! Maybe it should become an option in the settings.

**Comment by doomgrave** [comment]
Absolutly an add on feature needed, It could also keep only High IV (80%+) with also an high CP (maximum 20-30% less CP than max one captured)!

**Comment by Kekzy** [comment]
Why dont keep just keep  1x highest CP and 1x highest IV, so you can decide later if it is worth spending more dust etc

```
                      pokemonList
                      .GroupBy(p => p.PokemonId)
                      .Where(x => x.Count() > 1)
                      .SelectMany(p => p.Where(x => x.Favorite == 0)
                      .OrderByDescending(x => (x.IndividualAttack + x.IndividualDefense + x.IndividualStamina))
                      .ThenBy(n => n.StaminaMax)
                      .Skip(1)
                      .ToList());

                return pokemonList
                      .GroupBy(p => p.PokemonId)
                      .Where(x => x.Count() > 1)
                      .SelectMany(p => p.Where(x => x.Favorite == 0)
                      .OrderByDescending(x => x.Cp)
                      .ThenBy(n => n.StaminaMax)
                      .Skip(1)
                      .ToList());
```

**Comment by FeroxRev** [comment]
Ah this was already added in another PR !

**Pull request closed without merging**
