### PR TITLE
Google Login Made by @Maufeat

### PR DESCRIPTION
**Pull request by davidmann4**
Just a pull request for @Maufeat 's logic. Was not able to test it since
servers are down.

I really like my comand prompts verbose hehe - you can remove other messages

### CODE REVIEW

**Comment by davidmann4** [comment]
@Maufeat thanks for the great work!

**Comment by davidmann4** [comment]
Tested it, Works

**Comment by davidmann4** [comment]
hmm now it has merge conflict due the other merge

**Comment by FeroxRev** [comment]
Yeah looking into it now actually

**Comment by davidmann4** [comment]
should be easy to fix

**Comment by Maufeat** [comment]
If you dump the authToken which gets generated in the last 2 lines (_accessToken = authToken), try to dump that authToken then you can use that token ever and ever again. For example:

`        public async Task LoginGoogle(string authToken) <- here the token, you can use everytime.
        {
            _accessToken = authToken;
            _authType = AuthType.Google;
        }
`

**Comment by davidmann4** [comment]
maybe he merges and you add this change?

**Comment by davidmann4** [comment]
we also should create a config file for a .exe version

**Comment by Maufeat** [comment]
Would be great. Will try to write a .ini Reader

**Comment by FeroxRev** [comment]
Thanks guys, merged in, not sure why git doesn't reflect it

**Pull request closed without merging**
