### PR TITLE
Better logging and browser opening

### PR DESCRIPTION
**Pull request by depl0y**
I expanded the logging, and added opening a browser when using Google authentication.

### CODE REVIEW

**Comment by Spegeli** [comment]
I would change the Pokemon Logging Output to:

`
System.Console.WriteLine($"{DateTime.Now.ToString("HH:mm:ss")} Found {pokemons.Count()} catchable Pokemon");
`

**Comment by Spegeli** [comment]
And the other line into:
````
                System.Console.WriteLine(caughtPokemonResponse.Status == CatchPokemonResponse.Types.CatchStatus.CatchSuccess ? $"[{DateTime.Now.ToString("HH:mm:ss")}] We caught a {pokemon.PokemonId} with CP {encounterPokemonResponse?.WildPokemon?.PokemonData?.Cp} using a {balls_used} x {pokeball} and received XP { caughtPokemonResponse.Scores.Xp.Sum() }" : $"[{DateTime.Now.ToString("HH:mm:ss")}] {pokemon.PokemonId} with CP {encounterPokemonResponse?.WildPokemon?.PokemonData?.Cp} got away using a {pokeball}..");
````

**Comment by Spegeli** [comment]
And for the Google Website / Token it would be useful too if the Token automatic gets into your Clipboard ^^

**Comment by beminee** [comment]
`using System.Windows.Forms;`
`Clipboard.SetText("deviceCodeResponse.user_code");`

**Comment by Spegeli** [comment]
Clipboard.SetText is not working, getting a Error:

http://i.epvpimg.com/p1xMe.png

**Comment by jshield** [comment]
It will, as WinForms needs a STA Thread. You cannot just arbitrarily call it from any background thread.

You'll need to dispatch that to the main thread and make sure the main thread is marked STA

**Comment by Spegeli** [comment]
Or Simply:
````
            Thread thread = new Thread(() => Clipboard.SetText(deviceCodeResponse.user_code));
            thread.SetApartmentState(ApartmentState.STA); //Set the thread to STA
            thread.Start();
            thread.Join();
````

**Comment by beminee** [comment]
Yeah i forgot to mention [STAThread]

**Comment by jshield** [comment]
Don't put that into the API project though. You probably want to add a callback that passes it back from the auth method

**Pull request closed without merging**
