### PR TITLE
human walking rev3

### PR DESCRIPTION
**Pull request by UntilSunrise**
now with working algorithm for all regions in this world

### CODE REVIEW

**Comment by Mavmins** [comment]
Great work thanks. Can this be pulled By time soon @feroxrev

**Comment by AnthonyOSX** [comment]
@FeroxRev Get this pulled in :)

**Comment by DaniilSokolyuk** [comment]
Any test?

**Comment by DurtyFree** [comment]
Awesome! @FeroxRev pull it :dancer:

**Comment by UntilSunrise** [comment]
Can at least a few person test it and write their rough location here?

**Comment by UntilSunrise** [comment]
PocketMobsters - Today at 19:43 Uhr
@UntilSunrise Looks to be working fine in Sydney

For myself i can confirm that it work in Amsterdam(Netherlands) and Duisburg(Germany)

**Comment by skupfer** [comment]
```
[19:51:36] Starting Execute on login server: Google
[19:51:37] Transfer Psyduck with 210 CP
[19:51:38] Transfer Tentacool with 239 CP
[19:51:39] Distance to target location: 36,9296403946399 meters.
[19:51:43] Distance to target location: 35,5408788626437 meters.
[19:51:46] Distance to target location: 31,0981829744601 meters.
[19:51:49] Distance to target location: 26,6618495857141 meters.
[19:51:52] Distance to target location: 22,2219032042438 meters.
[19:51:55] Distance to target location: 17,7860267053435 meters.
[19:51:59] Distance to target location: 13,3461263591617 meters.
[19:52:02] Distance to target location: 8,91035028122518 meters.
[19:52:02] Farmed XP: 50, Gems: 0, Eggs:  Items: 2 x ItemPokeBall, 1 x ItemRevive
[19:52:18] Distance to target location: 9,08760335673046 meters.
[19:52:21] Distance to target location: 7,69817403850614 meters.
[19:52:24] We caught a Tentacool with CP 222 using a ITEM_POKE_BALL
[19:52:39] Distance to target location: 24,2408180982572 meters.
[19:52:43] Distance to target location: 22,852096469526 meters.
[19:52:46] Distance to target location: 18,4175403673139 meters.
[19:52:49] Distance to target location: 13,9793357678636 meters.
[19:52:52] Distance to target location: 9,53947570328592 meters.
[19:52:56] We caught a NidoranMale with CP 129 using a ITEM_POKE_BALL
```

**Comment by UntilSunrise** [comment]
Sefer - Today at 19:54 Uhr
@UntilSunrise confirmed its working

**Comment by Langleu** [comment]
@UntilSunrise working very well in Berlin, but maybe change the output to just 'Target location reached in x min' or just once 'next target in x meters'.
It might be a nice output for debugging but later it might just be too much, just my opinion.

**Comment by PocketMobsters** [comment]
Would not add this just yet, it makes you walk within 10 meters of targets when you can interact with objects within ~45 meters of you. Additionally the output feels pretty spammy, putting out an output every few seconds telling you how far away you are, 

Line 47 of Navigation.cs could be changed to 

                if (LocationUtils.CalculateDistanceInMeters(sourceLocation, targetLocation) < 30 && !notifiedClose)
                {
                    Logger.Write("We are within 30 meters of the target, attempting to interact");
                    notifiedClose = true;
                }`

With an addition 'bool notifiedClose = false;' around line 33

And modifying line 49 to have >= 30 instead of >= 10

**Comment by UntilSunrise** [comment]
@PocketMobsters had the same idea but used a little bit different implementation ;) Thanks anyway :+1:

**Comment by Mavmins** [comment]
that update works very well @UntilSunrise

**Comment by Mavmins** [comment]
@UntilSunrise is your speed calc in the settings file working properly ? I only ask because I set it to 10km/h but didnt get much in the way of credit towards egg hatching after 4 hours.

**Comment by jakesteele** [comment]
I still use your original commit, works wonders! Hopefully this can be merged into the main repo. Sucks having to re-patch it manually every time :D

**Comment by JordyLangen** [comment]
:+1:

**Comment by DaniilSokolyuk** [comment]
Tested, works fine

**Pull request merged**
