### PR TITLE
Abstracted logger

### PR DESCRIPTION
**Pull request by CookieNick**
I've abstracted the logger. Each message can have a 'Level', which can be logged or ignored depending on the settings.

The default 'ConsoleLogger' replicates the behavior currently used. It is no longer necessary to add the timestamp to every Console.WriteLine line, this is also handled by the ConsoleLogger.

Furthermore, the abstraction allows for different implementation of the logger. Using this, you can use the logs in any client built upon this API.

### CODE REVIEW

**Comment by jshield** [comment]
Good idea, why not log4net though?

**Comment by CookieNick** [comment]
I didn't want to add more complexion or dependencies and I think this would suffice. This implementation is easy enough but I think it's also powerful enough.

It would be easy to refactor to use log4net if needed later though.

**Comment by Spegeli** [comment]
I would prefer a Color Option.
This is currently my Logger:
`````
        public static void Normal(ConsoleColor color, string text)
        {
            ConsoleColor originalColor = System.Console.ForegroundColor;
            System.Console.ForegroundColor = color;
            System.Console.WriteLine($"[{DateTime.Now.ToString("HH:mm:ss")}] " + text);
            System.Console.ForegroundColor = originalColor;
        }
`````

**Comment by jshield** [comment]
@CookieNick fair enough, yeah probably should be up to the API consumer to provide a logger of choice.

**Comment by CookieNick** [comment]
Color is something that could be implemented later to the ConsoleLogger. The purpose of this PR is to abstract the logging, furher expansions are possible when this is merged.

**Comment by jshield** [comment]
Might I suggest adding ExtensionMethods (Logger.WriteError, Logger.WriteDebug, etc)

**Comment by FeroxRev** [comment]
Thanks for the ninja-merge :D 

Good idea jshields

**Pull request merged**
