### PR TITLE
Walk with randomized GPS coordiantes, lower capture delay, fix typo

### PR DESCRIPTION
**Pull request by mystexodus**

### CODE REVIEW

**Comment by AdnanCukur** [comment]
will egg hatching work with this ?

**Comment by mystexodus** [comment]
Yes it does!

**Comment by FeroxRev** [comment]
Bot logic should not reside in the api library class unfortunately. Also i'm unsure whether we want walking in the main branch. My bot has been running for long hours with current wait times and not receiving a soft ban. Perhaps in the future!

**Comment by mystexodus** [comment]
I'm not trying to avoid soft bans, I'm trying to humanize it to avoid the impending ban wave coming!

**Pull request closed without merging**
