### PR TITLE
Transfer Duplicates

### PR DESCRIPTION
**Pull request by thetemplar**

### CODE REVIEW

**Comment by Esummoner** [comment]
This would be better with a setting to keep the top 1-x number of pokemon.

**Comment by DaniilSokolyuk** [comment]
Amazing

**Comment by DaniilSokolyuk** [comment]
Or Ignore Favorite

**Comment by martin-podlubny** [comment]
might want to remove the `Client.TransferPokemon(...)` from this PR as it was introduced and merged in https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/50

**Comment by FeroxRev** [comment]
Merging and then moving to logic project

**Pull request merged**
