### PR TITLE
Add Client.TransferPokemon(...) and Client.EvolvePokemon(...)

### PR DESCRIPTION
**Pull request by martin-podlubny**
See title.

### CODE REVIEW

**Comment by ArcticXWolf** [comment]
+1, but why add the using statement on top? I had it just prefixed with InventoryResponse.Types.

**Comment by martin-podlubny** [comment]
@ArcticXWolf cleaner-looking code :)

**Comment by ArcticXWolf** [comment]
kk ^^

**Comment by Maufeat** [comment]
Nice! How would you do that, to check before TransferPokemon if it can Evolve?

**Comment by martin-podlubny** [comment]
@Maufeat try evolving it, see how it fails :D 

```C#
enum Holoholo.Rpc.Types.EvolvePokemonOutProto.Result {
	UNSET = 0;
	SUCCESS = 1;
	FAILED_POKEMON_MISSING = 2;
	FAILED_INSUFFICIENT_RESOURCES = 3;
	FAILED_POKEMON_CANNOT_EVOLVE = 4;
	FAILED_POKEMON_IS_DEPLOYED = 5;
}
```

Or do some clever specific-pokemon-aware pre-checks..

**Comment by martin-podlubny** [comment]
Utilizing shit from this PR in [Program.TransferAllGivenPokemons(...) and Program.EvolveAllGivenPokemons(...) #51](https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/51)

**Comment by FeroxRev** [comment]
Awesome!

**Pull request merged**
