### PR TITLE
Added a filter to pokemon evolve

### PR DESCRIPTION
**Pull request by yamashi**

### CODE REVIEW

**Comment by GamespikeYT** [comment]
is it possible to get more options in the app.config file lik for instance the evolve and transefer feature? There was another post from someone who edited you version of the API 
Pokemon-Go-Rocket-API-master (6).zip
here we can choose which modes we use for transfer etc

thanks for consideration

**Comment by MaxGriot** [comment]
This right here is just an api change, logic features for config will come if this gets pulled

**Comment by yamashi** [comment]
This is just an api feature, a logic feature with config and such will come when we have all api features ready and stable.

**Comment by problemz** [comment]
I made a list of all Pokemon from Base to first Evolution if they have at least 1. I use it for me, but if this PR gets in, we have it ready to add.

`/* 1-Evo Pokemons*/ PokemonId.Rattata, PokemonId.Spearow, PokemonId.Ekans, PokemonId.Pikachu, PokemonId.Sandshrew, PokemonId.Clefable,
                                                                                                    PokemonId.Vulpix, PokemonId.Jigglypuff, PokemonId.Zubat, PokemonId.Paras, PokemonId.Venonat, PokemonId.Diglett,
                                                                                                    PokemonId.Meowth, PokemonId.Psyduck, PokemonId.Mankey, PokemonId.Growlithe, PokemonId.Tentacool, PokemonId.Ponyta,
                                                                                                    PokemonId.Slowpoke, PokemonId.Magnemite, PokemonId.Doduo, PokemonId.Seel, PokemonId.Grimer, PokemonId.Shellder,
                                                                                                    PokemonId.Drowzee, PokemonId.Krabby, PokemonId.Voltorb, PokemonId.Exeggcute, PokemonId.Cubone, PokemonId.Koffing,
                                                                                                    PokemonId.Rhyhorn, PokemonId.Horsea, PokemonId.Goldeen, PokemonId.Staryu, PokemonId.Magikarp, PokemonId.Eevee,
                                                                                                    PokemonId.Omanyte, PokemonId.Kabuto, PokemonId.Dratini,
                                                                                /* 2-Evo Pokemons*/ PokemonId.Bulbasaur, PokemonId.Charmender, PokemonId.Squirtle, PokemonId.Caterpie, PokemonId.Weedle, PokemonId.Pidgey,
                                                                                                    PokemonId.NidoranFemale, PokemonId.NidoranMale, PokemonId.Clefary, PokemonId.Oddish, PokemonId.Poliwag, PokemonId.Abra,
                                                                                                    PokemonId.Machop, PokemonId.Bellsprout, PokemonId.Geoduge, PokemonId.Gastly`

**Comment by MaxGriot** [comment]
@problemz thanks for the list, I have taken the list of first evolutions and remove magikarp and eevee from the list.

**Pull request merged**
