### PR TITLE
Added PokeStop Name, Catch Pokemon Experience and XP Counter.

### PR DESCRIPTION
**Pull request by nowayrlz**
Just Added somethings already posted here and some tweaks.

### CODE REVIEW

**Comment by Spegeli** [comment]
I would the WriteLine for Pokestop Output to:
`                System.Console.WriteLine($"[{DateTime.Now.ToString("HH:mm:ss")}] Using Pokestop: {fortInfo.Name}");
                System.Console.WriteLine($"[{DateTime.Now.ToString("HH:mm:ss")}] Farmed XP: {fortSearch.ExperienceAwarded}, Gems: { fortSearch.GemsAwarded}, Eggs: {fortSearch.PokemonDataEgg} Items: {StringUtils.GetSummedFriendlyNameOfItemAwardList(fortSearch.ItemsAwarded)}");
`

**Comment by nowayrlz** [comment]
Done ;)

**Comment by Spegeli** [comment]
What should caughtPokemonResponse.Scores.X return?
Currently it returns [ 100, 100, 10 ] and i dont know what this values are?!

**Comment by jshield** [comment]
That looks like [caught pokemon xp, bonus xp, throw xp] to me

**Comment by Spegeli** [comment]
Ah your right.
Will take a look if i can add up the XP befor output them.

**Comment by nowayrlz** [comment]
That was just to see if repeat task was getting over and executing the pokemon transfer.
await _inventory.GetMyPokemon(); Nvm, was trying to make auto evolve pokemons... Just got too lazy

**Comment by Spegeli** [comment]
Anyone know a solution how to add up: [ 100, 100, 10 ] ?

**Comment by jshield** [comment]
https://msdn.microsoft.com/en-us/library/bb548651(v=vs.110).aspx

**Comment by nowayrlz** [comment]
It's summing now

**Comment by Spegeli** [comment]
No change it to a cleaner output:
`
System.Console.WriteLine(caughtPokemonResponse.Status == CatchPokemonResponse.Types.CatchStatus.CatchSuccess ? $"[{DateTime.Now.ToString("HH:mm:ss")}] We caught a {pokemon.PokemonId} with CP {encounterPokemonResponse?.WildPokemon?.PokemonData?.Cp} using a {pokeball} and received XP: { caughtPokemonResponse.Scores.Xp.Sum() }" : $"[{DateTime.Now.ToString("HH:mm:ss")}] {pokemon.PokemonId} with CP {encounterPokemonResponse?.WildPokemon?.PokemonData?.Cp} got away using a {pokeball}..");
`
and we all are happy ;-)

**Comment by Spegeli** [comment]
Maybe you want to add a last small think:

```
            if (pokemons != null && pokemons.Any())
                System.Console.WriteLine($"[{DateTime.Now.ToString("HH:mm:ss")}] Catchable Pokemon near us. Doing PokeBattle:");
```
under
```
var pokemons = mapObjects.MapCells.SelectMany(i => i.CatchablePokemons);
```
which gives us the following output:

> [08:31:05] Catchable Pokemon near us. Doing PokeBattle:
[08:31:06] We caught a Spearow with CP 353 using a ITEM_GREAT_BALL and received XP 210
[08:31:11] We caught a Kakuna with CP 196 using a ITEM_POKE_BALL and received XP 210

So i dont need a extra PullRequest for this small addition ;-)

**Comment by AssHole12** [comment]
Works, but it delays a bit

**Comment by Spegeli** [comment]
@nowayrlz: Can you add the current Stardust Sum to the BarState?

**Comment by FeroxRev** [comment]
Could you add BotStats.cs?

**Comment by nowayrlz** [comment]
It can't be merged cause someone changed System.Console.WriteLine to Logger....

**Pull request closed without merging**
