### PR TITLE
simulate more human like walking instead of teleporting. Because of t…

### PR DESCRIPTION
**Pull request by UntilSunrise**
…his we can reduce the delay between stops.

It also take more than 5 secs to catch a pokemon.

### CODE REVIEW

**Comment by davidmann4** [comment]
would be also nice if he would walk to nearest pokestops first, do not think that this is teh case atm

**Comment by davidmann4** [comment]
cant we uzse any libs for this? also walking on streets would be fancy - maybe related to #18

**Comment by AlginMaduro** [comment]
I was also looking into this, but my solution used stackoverflow.com/questions/6366408/calculating-distance-between-two-latitude-and-longitude-geocoordinates.

But you beat me to it :(

**Comment by StealthyXor** [comment]
i created these helper methods in utils for myself...
https://gist.github.com/StealthyXor/1c03589a45ac6a29c4c4ab3dfbf93e9d

what i do is:

calculate the distance between the current location and the object location...
divide this distance by the amount of steps per waypoint you want to move...

then divide the line between A and B, in this amount of points;

then just iterate through the list, waiting as long as you want per iteration....

**Comment by OranShuster** [comment]
you could add a calculation to keep track of total distance traveled using a simple formula

        public double Distance(double lat1, double lon1,double lat2,double lon2)
        {
            double R = 6371;

            double dLat = toRadian(lat2 - lat1);
            double dLon = toRadian(lon2 - lon1);

            double a = Math.Sin(dLat / 2) * Math.Sin(dLat / 2) +
                Math.Cos(this.toRadian(lat1)) * Math.Cos(this.toRadian(lat2)) *
                Math.Sin(dLon / 2) * Math.Sin(dLon / 2);
            double c = 2 * Math.Asin(Math.Min(1, Math.Sqrt(a)));
            double d = R * c;

            return d;
        }

        private double toRadian(double val)
        {
            return (Math.PI / 180) * val;
        }

and in UpdatePlayerLocation we do before doWalk()
            var oldLat = _currentLat;
            var oldLon = _currentLng;

and after all the ifs
            distanceWalked += Distance(oldLat, oldLon, _currentLat, _currentLng);
            Console.WriteLine("Total distance walked in meters = " + distanceWalked.ToString());

**Comment by StealthyXor** [comment]
something like this
http://i.imgur.com/6gd0I4L.png

**Comment by rfaes** [comment]
It should check during the walk for pokemons. It looks like the viewing radius is something around 70 meters. So it should check all 35 meters, or with the average walking speed of 1.4m/s every 25 seconds. 
I've modified the code to do that, I will create a pull request as soon as I am home.

**Comment by OranShuster** [comment]
i think the program sees way more than 70. i tried it now and it started walking to a point 400 meters from me

**Comment by StealthyXor** [comment]
image

.OrderBy(i => Utils.GetDistance(client.GetCoordinates(), new GeoCoordinate(i.Latitude, i.Longitude)));

**Comment by OranShuster** [comment]
Damn, you are doing exactly the same thing as i am

**Comment by FeroxRev** [comment]
Not merging this in right now, because i will focus on API part next days and not bot logic. Good work though, so will probably merge this later

**Comment by pkiers** [comment]
Thanks all, also have it working version with all ideas/samples here :)

image

**Comment by DaniilSokolyuk** [comment]
Maybee speed instead of StepDistance ?

**Comment by MonsterMMORPG** [comment]
what does step distance mean? how many meter we move each second?

**Comment by UntilSunrise** [comment]
I change my latitude longitude coords +-0.000095 until i reach my destination, so StepDistance should be fine.
Unfortunately every movement looks like an "L" shape, because of my algorithm.

**Comment by MonsterMMORPG** [comment]
Still better than teleport 

How can we ourselves merge this with the project

**Comment by MonsterMMORPG** [comment]
@UntilSunrise how can i locally merge your pull?

here question http://stackoverflow.com/questions/38483302/how-can-i-fetch-unmerged-pull-requests-that-i-do-not-own

**Comment by UntilSunrise** [comment]
You can sync your branch with my branch:

First step: https://help.github.com/articles/configuring-a-remote-for-a-fork
Second step https://help.github.com/articles/syncing-a-fork/

**Comment by MonsterMMORPG** [comment]
@UntilSunrise  i never taught using github will be this hard

still i can not make it work

**Comment by MonsterMMORPG** [comment]
i have manually copy pasted on v5 and getting this error

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'HttpClient' does not contain a definition for 'PostProtoPayload' and no extension method 'PostProtoPayload' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)	PokemonGo.RocketAPI	D:\74 pokemon go\CatcherStopperTransfer\PokemonGo\RocketAPI\Client.cs	271	Active
`

**Comment by MonsterMMORPG** [comment]
ok i have made it work. constantly "keep restart error" giving app now works super awesome

ty

**Comment by MonsterMMORPG** [comment]
@UntilSunrise  can you please improve the search logic for hunting pokemon rather than pokestop farm?

**Comment by aertheron** [comment]
Is there any chance this will get into the main branch anytime soon?
This will help decrease soft-bans a lot for locations with PokeStops that are a bit to far apart.

Also thank you everybody, great work!

**Comment by FeroxRev** [comment]
I'd like to merge this in, however this should not be part of Client.cs, but rather the logic part (which is currently in program.cs but will soon be moved out. Once moved out, could you adopt it in the logic part please?). Closing this PR

**Pull request closed without merging**
